requires_core: ^3.0.0
dependencies:
  - artifactId: integration-httpserver
    groupId: com.ecat
    version: ^3.0.0
  - artifactId: integration-ecat-core-api
    groupId: com.ecat
    version: ^3.0.0
